### ISSUE TITLE
Run Image Smoke Tests as Part of CI

### ISSUE THREAD

**Issue by dallinb** [cbdq-io/docker-flyte#71]
Run smoke tests for:

- [x] Pandas
- [x] Spark
- [x] Delta Lake

**Comment by dallinb** [comment]
Working on this on the `bugfix/71-smoke-tests` branch.  Pandas and Spark is done.  However having weird issues on delta.  When I run:

```shell
docker run --rm -it flyte:latest pyspark --packages io.delta:delta-spark_2.12:3.1.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
```

and then execute:

```python
import pyspark
from delta import *
```

all works OK.  However, when I run:

```shell
docker run --rm -it -v "${PWD}/examples/delta:/examples" flyte:latest spark-submit --packages io.delta:delta-spark_2.12:3.1.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" /examples/delta.py
```

I get:

```
Traceback (most recent call last):
  File "/examples/delta.py", line 2, in <module>
    from delta import *
  File "/examples/delta.py", line 8, in <module>
    spark = configure_spark_with_delta_pip(builder).getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'configure_spark_with_delta_pip' is not defined
```

Will investigate further.
